version: '3'

services:
    api:
        build:
            context: ./backend
            dockerfile: Dockerfile-dev
        ports:
            - "3000:3000"
        volumes:
            - "./backend:/app"
    
    web:
        build:
            context: ./frontend
            dockerfile: Dockerfile-dev
        ports:
            - "8080:8080"
        volumes:
            - "./frontend:/app"
