version: '3.0'

services:
    web:
        build: ./frontend
        ports:
            - "8080:80"
        depends_on:
            - api
    
    api:
        build: ./backend
        ports:
            - "3000:80"
        volumes:
            - "./backend:/app"
        depends_on:
            - db

    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - "./postgres-data:/var/lib/postgresql/data"
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - db
